### ISSUE TITLE
Observations profile: data_queries - Limit types of queries

### ISSUE THREAD

**Issue by ways** [EURODEO/rodeo-edr-profile#12]
Mandatory support for:
- locations

The rest are optional.

Consider requiring a specific coveragejson response format (which can be validated).

**Comment by havardf** [comment]
Should probably have mandatory locations and area support. Positions as optional, but encouraged?  

However, its not clear how a position query actually works when the dataset is a set of points. Require snap to nearest, but with a max range? If so, then maybe radius actually makes more sense?
