### ISSUE TITLE
Move validator to this repo?

### ISSUE THREAD

**Issue by ways** [EURODEO/rodeo-edr-profile#13]
Having the validator as part of this repo will allow us to keep profile and validator in sync, and require every rule to be accompanied with code for testing.

On the other hand, the validator is not limited to this profile, it will be testing general EDR as well.

**Comment by ways** [comment]
Validator repo: https://github.com/metno/sedr

**Comment by tomkralidis** [comment]
I would keep software outside of this repository, whose main goal is to specify and describe the profile itself.

**Comment by havardf** [comment]
We discussed this a bit more in various forums and concluded that we should keep the validator and the profile in separate repos.

So, we need to figure some other mechanism for ensuring that the validator will be up to date with the profile.
