### ISSUE TITLE
Binary data output allowed in EDR?

### ISSUE THREAD

**Issue by geira** [EURODEO/rodeo-edr-profile#17]
Another question for the EDR standards authorities:

In addition to numeric data in various human-readable formats we also distribute a lot of binary data, e.g. GRIB files, radar images, vertical profile plots, satellite images et al. Initially we thought these could easily be downloaded using EDR, but then I found this passage in the [OGC API Common guide](https://docs.ogc.org/guides/20-071.html#toc18):

> 8.1. Definition [...]
> 1. An OGC API Collection may only contain data. It does not encompass non-data [resources](https://docs.ogc.org/guides/20-071.html#definition-resource) (but the Collection resource may still have related auxiliary resources, such as schemas, or processes, as sub-resources).

Can't find the definition of "data" anywhere, but in [5.1](https://docs.ogc.org/guides/20-071.html#toc11) there is a definition of "dataset":

> A dataset can be a vector feature collection, a coverage/imagery, or a collection of datasets (therefore potentially a mix of any of these things).

Wondering if it implies that a non-queriable blob that can only be downloaded as a complete file is unsuitable for spatial/temporal search using EDR or not?

**Comment by m-burgoyne** [comment]
@geira The EDR Items query can be used to download non-queriable blob's and supports spatial/temporal search query parameters (bbox and datetime).
