### ISSUE TITLE
How to avoid naming collisions in EDR aggregators

### ISSUE THREAD

**Issue by geira** [EURODEO/rodeo-edr-profile#18]
Suggest you start by watching [this video](https://www.youtube.com/watch?v=dYyT7GrHNX4), outlining the functionality of a working EDR aggregation service.

My immediate questions was how to avoid naming collisions in collections when combining multiple data producers. Their answer was "the ongoing EDR profile work [...] should address this, lead by Håvard /MetNo". So we need to find a way to resolve this, which partly overlaps the closed issue #5 (which I think should be reopened).

**Comment by geira** [comment]
Answer from KNMI:

> The aggregator will support “mapping” of collections (i.e. the source collection with name “X” is exposed by the aggregator as collection “Y”). But in a sense, collisions is what we want, as we want the aggregator to be able to merge the datasets of different countries into one! This should also be configurable in the aggregator (i.e. these specific source collections for these sources should be merged into one aggregator collection).

**Comment by Teddy-1000** [comment]
Based on the answer from KNMI, I suggest we set a specific set of `{collectionID}` in this profile. I think this is outside the spec of core, and should be defined in the requirement class for each sub-spec, observarions, forcast etc.

**Comment by havardf** [comment]
Agreed.
