### ISSUE TITLE
Constraints on the title of a collection

### ISSUE THREAD

**Issue by havardf** [EURODEO/rodeo-edr-profile#5]
Typical use-case: Client populates a selection menu with `title` of collections. 

Some potential rules:
- Mininum and maxium number of characters.
- No acronyms.
- How to handle multiple languages? Should we handle multiple languages?

**Comment by mrauhala** [comment]
We should handle multiple languages. I think best way to do that is to have parameter such as lang=fi and then responses would be in that language. CoverageJSON does have something for the i18n, but that does not solve the whole problem.

**Comment by mrauhala** [comment]
Title is now missing from many of the services. Should we say that it is mandatory, otherwise clients will default to collection id, which is maybe not optimal for user interfaces and leads to not optimal lists for the user.

**Comment by havardf** [comment]
I yes definately yes. Maybe like this:

Mandatory and with the following rules:
- max 50 characters
- english text
- Describe the collection topicly and geographically. As in, "Surface observations in Europe" for E-SOH, not just "Observations".

**Comment by mrauhala** [comment]
There have been a lot of discussion internally in FMI about naming conventions, it is not easy, but one thing we observed was that names should have the most "important" bit first / near beginning of the string so if UI needs to truncate title, relevant part is not dropped. Your example follows this "Surface observations in Europe"

**Comment by geira** [comment]
Prohibiting acronyms could cause problems when they are often more recognizable than what they originally stand for, e.g.

- TAF/METAR
- CBRN
- MEPS
- NOAA
- ECMWF

**Comment by tomkralidis** [comment]
A title of "surface weather observations from NOAA" is not helpful to the actual content.  Here, "NOAA" is a property of the entire record, as the organization.

**Comment by geira** [comment]
I actually had a specific example in mind:

https://labs.metoffice.gov.uk/edr/collections?f=html

**Comment by tomkralidis** [comment]
Which collection?  I am guessing the collections with "UK" as part of the title (perhaps "Airfields in the United Kingdom" would work better here?).

**Comment by geira** [comment]
Ignoring "UK" and "EDR", the following collections have titles with acronyms which would exceed the 50 char limit if expanded:

- Met Office (UKV) station level
- Met Office (UKV) Soil Temperatures
- Met Office (UKV) data at standard heights
- Met Office (UKV) data at standard pressure levels
- Met Office (UKV) whole atmosphere
- ECMWF (Global) station level ensemble medium-range forecasts
- ECMWF (Global) isobaric levels ensemble medium-range forecasts
- ECMWF AIFS Machine Learning surface data
- ECMWF AIFS Machine Learning isobaric data
- NOAA Graphcast station level data
- NOAA Graphcast isobaric data

**Comment by tomkralidis** [comment]
What value does "NOAA" have in an actual title?  Can a user not derive this from the collection metadata itself?

**Comment by geira** [comment]
Well, the only other relevant metadata field available under /edr/collections is `description`, which is not always displayed unless reading the JSON manually (e.g. you can't see it when using [Swagger UI](https://wp5-rodeo-test.dmi.govcloud.dk/docs#/default/collection_by_id_metadata_collections__collection_id__get)).

**Comment by tomkralidis** [comment]
Is Swagger UI a requirement then?  Note that there needs to be some provision around `description` for fulsome, descriptive metadata.
