### ISSUE TITLE
Links in a collection - require a link to license

### ISSUE THREAD

**Issue by ways** [EURODEO/rodeo-edr-profile#9]
License for usage of the data.

Open question: should we require unified links to known licenses (for example CC), or allow links to any random license?

**Comment by mrauhala** [comment]
To make it easier to understand this issue. This is how UKMO test server is displaying license in links section of collection. 
`        {
            "href": "https://creativecommons.org/licenses/by-nc-nd/4.0/",
            "hreflang": "en",
            "rel": "licence",
            "type": "text/html"
        },`

**Comment by mrauhala** [comment]
> @mrauhala What do you think? Is it ok to include public domain there? Are there other licenses that should be there?
Yes public domain is ok, I guess other variants of cc by are needed as well.

**Comment by havardf** [comment]
@mrauhala Are there any constraints through EU Data directive and/or EUMETNET and WMO relevant to this list of licenses?

**Comment by mrauhala** [comment]
> @mrauhala Are there any constraints through EU Data directive and/or EUMETNET and WMO relevant to this list of licenses?

HVD Implementation Act states about license:
* under the conditions of the Creative Commons BY 4.0 licence or any equivalent or less restrictive open licence;

Reference: https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2023.019.01.0043.01.ENG

**Comment by havardf** [comment]
Great! I interpret that as it will be enough to list those two licenses in our profile as well?

**Comment by geira** [comment]
Our data are actually governmentally required to be dual-licenced (currently CC BY 4.0 plus [NLOD 2.0](https://data.norge.no/nlod/en/2.0)). Not sure if you can specify more than one licence in EDR?
